name: projectnawi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.2
  google_ml_kit: ^0.19.0  #0.7.0
  google_mlkit_text_recognition: ^0.14.0 #^0.3.0
  google_fonts: ^4.0.3
  tflite_v2: ^1.0.0
  camera: ^0.11.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0
  ultralytics_yolo: ^0.0.7
  wakelock_plus: ^1.3.2
  #wakelock: ^0.6.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2


  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/detect.tflite
    - assets/labelmap.txt
    - assets/model.tflite  # Agregado el nuevo modelo
    - assets/labels.txt    # Etiquetas del modelo de billetes
    - assets/logo.png
    - assets/blindimg2.jpeg

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

